import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { createTestApi, loginAsDefault } from "./helpers";
import type { TestApiClient } from "./fixtures";

const evidenceDir = resolve(process.env.MULTICA_PROGRESS_QA_DIR ?? "test-results/issue-progress-evidence");
let api: TestApiClient;
test.beforeEach(async ({ page }) => {
  page.on("pageerror", error => console.log("Progress QA browser error:", error.message));
  api = await createTestApi();
  await mkdir(evidenceDir, { recursive: true });
});
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus) await page.screenshot({ path: testInfo.outputPath("failure.png") });
  await api?.cleanup();
});

test("remaining work finds deep prerequisites and refreshes without completing the parent", async ({ page }) => {
  test.setTimeout(120_000);
  const workspace = await loginAsDefault(page);
  const project = await api.createProject("E2E payment progress");
  const root = await api.createIssue("E2E payment goal", { status: "in_progress", project_id: project.id });
  const parent = await api.createIssue("E2E integration branch", { status: "in_progress", parent_issue_id: root.id, project_id: project.id });
  const leaf = await api.createIssue("E2E deep callback fix · 回调异常处理与联调验收 · ".repeat(8), { status: "blocked", parent_issue_id: parent.id, project_id: project.id });
  const prerequisite = await api.createIssue("E2E prerequisite API repair", { status: "todo", project_id: project.id });
  const intermediate = await api.createIssue("E2E integration prerequisite", { status: "todo", project_id: project.id });
  await api.createIssue("E2E accepted child", { status: "done", parent_issue_id: root.id, project_id: project.id });
  await api.createIssue("E2E removed scope", { status: "cancelled", parent_issue_id: root.id, project_id: project.id });
  await api.createIssueDependency(leaf.id, intermediate.id);
  await api.createIssueDependency(intermediate.id, prerequisite.id);
  await page.goto(`/${workspace}/issues/${root.id}`, { waitUntil: "domcontentloaded" });
  const progress = page.locator("[data-issue-work-progress]");
  await expect(progress.getByText("Unfinished: 2", { exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(progress.getByText("Completed: 1", { exact: true })).toBeVisible();
  await expect(progress.getByText("Ended without completion: 1", { exact: true })).toBeVisible();
  await expect(progress.getByRole("button", { name: "Direct sub-issues", exact: true })).toHaveAttribute("aria-pressed", "true");
  await progress.getByRole("button", { name: "Remaining work", exact: true }).click();
  const leafRow = progress.locator(`[data-progress-issue-id="${leaf.id}"]`);
  await expect(leafRow.getByText("Final prerequisites", { exact: true })).toBeVisible();
  await expect(leafRow.getByRole("link", { name: new RegExp("E2E prerequisite API repair") }).last()).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await progress.screenshot({ path: resolve(evidenceDir, "remaining-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(leafRow).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await progress.screenshot({ path: resolve(evidenceDir, "remaining-narrow.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  const mine = progress.getByRole("checkbox", { name: "Needs my action", exact: true });
  await mine.focus();
  await page.keyboard.press("Space");
  await expect(mine).toBeChecked();
  await page.keyboard.press("Space");
  await expect(mine).not.toBeChecked();
  await expect(leafRow).toBeVisible();
  await api.updateIssue(leaf.id, { status: "done" });
  await expect(progress.getByText("Unfinished: 1", { exact: true })).toBeVisible({ timeout: 15_000 });
  await expect(progress.locator(`[data-progress-issue-id="${leaf.id}"]`)).toHaveCount(0);
  await expect(progress.locator(`[data-progress-issue-id="${parent.id}"]`).getByText("Descendants ended; parent unfinished", { exact: true })).toBeVisible();
  await page.goto(`/${workspace}/projects/${project.id}`, { waitUntil: "domcontentloaded" });
  await page.getByRole("button", { name: "Needs attention", exact: true }).click();
  const attention = page.getByRole("region", { name: "Needs attention", exact: true });
  await expect(attention.locator(`[data-progress-issue-id="${parent.id}"]`)).toBeVisible();
  await attention.screenshot({ path: resolve(evidenceDir, "project-attention.png") });
});

test("attention surfaces the designated member's request and keeps its existing response flow", async ({ page }) => {
  test.setTimeout(120_000);
  const workspace = await loginAsDefault(page);
  const project = await api.createProject("E2E decision progress");
  const issue = await api.createIssue("E2E decision delivery", { status: "in_review", project_id: project.id });
  const request = await api.createHumanRequestFixture(issue.id, { key: "acceptance", kind: "confirmation", title: "确认验收结论", steps: ["核对交付结果后确认。"], action_label: "确认继续", next: "我会根据结论继续推进。" });
  await page.goto(`/${workspace}/projects/${project.id}?project_tab=attention`, { waitUntil: "domcontentloaded" });
  const attention = page.getByRole("region", { name: "Needs attention", exact: true });
  await expect(attention.locator(`[data-progress-issue-id="${issue.id}"]`).getByText("Awaiting my decision", { exact: true })).toBeVisible({ timeout: 30_000 });
  await attention.getByRole("checkbox", { name: "Needs my action", exact: true }).check();
  const row = attention.locator(`[data-progress-issue-id="${issue.id}"]`);
  await row.getByRole("button", { name: "View run", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.screenshot({ path: resolve(evidenceDir, "attention-run.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await row.locator("summary", { hasText: "Respond to request" }).click();
  const card = row.locator(`[data-human-request-id="${request.id}"]`);
  await expect(card.getByRole("button", { name: "确认继续", exact: true })).toBeVisible();
  await attention.screenshot({ path: resolve(evidenceDir, "attention-human-request.png") });
  const submitted = page.waitForResponse(response => response.url().endsWith(`/human-requests/${request.id}/respond`) && response.request().method() === "POST");
  await card.getByRole("button", { name: "确认继续", exact: true }).click();
  const response = await submitted;
  expect(response.status()).toBe(200);
  expect(response.request().postDataJSON()).toEqual({ revision: request.revision, decision: "approve" });
  await expect(row).toHaveCount(0, { timeout: 15_000 });
  await expect(attention.getByText("No issues match these filters.", { exact: true })).toBeVisible();
});

test("an unsupported progress endpoint leaves existing sub-issue operations available", async ({ page }) => {
  const workspace = await loginAsDefault(page);
  const parent = await api.createIssue("E2E old service parent", { status: "in_progress" });
  const child = await api.createIssue("E2E original child", { parent_issue_id: parent.id, status: "todo" });
  await page.route(`**/api/issues/${parent.id}/progress?**`, route => route.fulfill({ status: 404, contentType: "application/json", body: JSON.stringify({ error: "route not found" }) }));
  await page.goto(`/${workspace}/issues/${parent.id}`, { waitUntil: "domcontentloaded" });
  const progress = page.locator("[data-issue-work-progress]");
  await expect(progress.getByRole("alert")).toBeVisible({ timeout: 15_000 });
  await expect(progress.getByRole("button", { name: "Direct sub-issues", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(progress.getByText(/E2E original child/)).toBeVisible();
  await expect(progress.getByText(/No unfinished descendants/)).toHaveCount(0);
  await api.updateIssue(child.id, { status: "done" });
  await expect(progress.getByText("1/1", { exact: true })).toBeVisible({ timeout: 15_000 });
});
