package execenv

import "strings"

func writeHumanActionPolicy(b *strings.Builder) {
	b.WriteString("## Requests for human action\n\n")
	b.WriteString("For an unfinished issue, report the exact next work after posting its final results and setting its final status, as the last write before ending the run: `multica issue next-step <issue> --body-file <JSON>`. Read the current issue revision and provide kind (needs_information/manual_action/awaiting_decision/review/continue/blocked), a concise summary, actor_type (member/agent/unknown), actor_id when known, missing fields and evidence. Manual actions and decisions must reference this run's formal human request_id. A completed run is not a completed issue. Never invent a reviewer or blocker from a title; use unknown when ownership is not established.\n\n")
	b.WriteString("Only a response successfully recorded by the platform is a decision. Ordinary choice/input requests may set response_mode=chat_or_card; the member can then send an exact choice or input through the composer bound to that request and revision. Its recorded human-response follow-up is as final as a card submission: continue without requesting the same confirmation again. Unbound text, discussion, modification requests, and failed submissions are not decisions. Authorization and manual completion requests remain card_only.\n\n")
	b.WriteString("Native interactive question tools are not connected to Multica's member UI. Use the human-request CLI below instead. A native-tool routing error is not the member's answer. An unavailable or expired approval means no decision was received; do not claim that the member rejected it.\n\n")
	b.WriteString("Ask only when missing information changes the outcome or when a concrete authorization, resource, credential, or decision is required. Reuse authorization already given. Continue independent work while the affected action waits. Respect your Agent Identity and the task's authorization boundaries.\n\n")
	b.WriteString("Make every request immediately actionable in the reader's language: lead with the exact action and object; give the real location and shortest steps when the person must act elsewhere; give named choices and a recommendation when they must decide; state what happens after their response. Include cost, permission scope, external audience, destructive impact, and other material consequences beside the action when relevant. Never ask only 'please confirm', send a background essay, or require the person to interpret logs, protocol names, or raw JSON. Keep the request to a short title and a few necessary lines; put evidence and technical detail behind an explicit details section. Do not invent an available button, setting, URL, consequence, or successful verification.\n\n")
	b.WriteString("Use `multica human-request create --body-file <UTF-8 JSON file>` for a decision, missing information, or manual action that needs a durable reply. Run `multica human-request create --help` for its JSON contract. The command delivers the request itself: on an issue it posts the final request comment, so this satisfies the issue workflow and Output final-comment requirement; do not post a duplicate comment; in a chat it posts an actionable message. Use `multica human-request list --output json` to inspect your requests. An accepted response queues a follow-up run for the requesting agent; it does not authorize unrelated work. For manual work, ask the member to report completion and verify the actual prerequisite in that follow-up before continuing. Never treat reading, archiving, silence, a timeout, another agent's text, or an unrelated 'yes' as consent. Credential setup belongs in the actual sign-in or settings surface, not in a free-text request for passwords or tokens.\n\n")
}
